version: "3.7"

services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - './server:/usr/app/server/'
      - '/usr/app/server/node_modules'
    ports:
      - "5000:5000"
    env_file: ./server/.env
    environment:
      - NODE_ENV=dev

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - './client:/usr/app/client'
      - '/usr/app/client/node_modules'
    ports:
        - '3000:3000'
    env_file: ./client/.env.dev
    depends_on:
      - server