version: "3.7"

services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - './server:/usr/src/app/server'
      - '/usr/src/app/server/node_modules'
    expose:
      - 5000
    ports:
      - "5000:5000"
    command: nodemon
    env_file: ./server/.env

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    stdin_open: true
    volumes:
      - './client/:/usr/src/app/client'
      - '/usr/src/app/client/node_modules'
    expose:
      - 3000
    ports:
        - '3000:3000'
    command: npm start
    depends_on:
      - server